import { internalMutation } from "../../convex/_generated/server";
import { v } from "convex/values";
import { Id } from "../../convex/_generated/dataModel";

export const addSampleIndividuals = internalMutation({
  args: {},
  handler: async (ctx) => {
    // Check if individuals already exist
    const existingIndividuals = await ctx.db.query("individuals").collect();
    if (existingIndividuals.length > 0) {
      return existingIndividuals.map(individual => individual._id);
    }

    // Get Gaza region ID (from createSampleRegions)
    const gazaRegion = await ctx.db
      .query("regions")
      .filter(q => q.eq(q.field("name"), "Gaza Strip"))
      .unique();

    if (!gazaRegion) {
      throw new Error("Gaza Strip region not found. Please run createSampleRegions first.");
    }

    // Sample individual data
    const individuals = [
      {
        Name: "Christina Ward",
        Origin: "Mexico",
        Location_Type: "Urban",
        Event_Severity: 66.38669849037136,
        Economic_Loss_USD: 2231.75,
        Shelter_Status: "None",
        Food_Water_Access: "Partial",
        Health_Risk: "No Risk",
        Health_Severity_Score: 0.0,
        Family_Size: 5,
        Time_Since_Displacement_Days: 190,
        Displacement_Start_Date: "2024-10-18",
        Displacement_End_Date: "2025-12-06",
        Age: 6,
        Age_Group: "Child (0-17)",
        Shelter_Status_Num: 1.0,
        Food_Water_Access_Num: 0.5,
        Location_Type_Num: 0.3,
        Age_Group_Num: 1.0,
        Urgency_Score: 57.14660565942685,
        regionId: gazaRegion._id,
      },
      {
        Name: "Bradley Jackson",
        Origin: "Bhutan",
        Location_Type: "Urban",
        Event_Severity: 71.14382328837071,
        Economic_Loss_USD: 2183.45,
        Shelter_Status: "Partial",
        Food_Water_Access: "Partial",
        Health_Risk: "No Risk",
        Health_Severity_Score: 0.0,
        Family_Size: 8,
        Time_Since_Displacement_Days: 438,
        Displacement_Start_Date: "2024-02-13",
        Displacement_End_Date: "2025-05-01",
        Age: 36,
        Age_Group: "Adult (18-59)",
        Shelter_Status_Num: 0.5,
        Food_Water_Access_Num: 0.5,
        Location_Type_Num: 0.3,
        Age_Group_Num: 0.0,
        Urgency_Score: 47.87598281916372,
        regionId: gazaRegion._id,
      },
      {
        Name: "Charles Simmons",
        Origin: "Botswana",
        Location_Type: "Rural",
        Event_Severity: 76.79023024504636,
        Economic_Loss_USD: 2481.9,
        Shelter_Status: "Partial",
        Food_Water_Access: "Partial",
        Health_Risk: "No Risk",
        Health_Severity_Score: 0.0,
        Family_Size: 7,
        Time_Since_Displacement_Days: 32,
        Displacement_Start_Date: "2025-03-25",
        Displacement_End_Date: "2026-03-18",
        Age: 10,
        Age_Group: "Child (0-17)",
        Shelter_Status_Num: 0.5,
        Food_Water_Access_Num: 0.5,
        Location_Type_Num: 0.7,
        Age_Group_Num: 1.0,
        Urgency_Score: 55.21483648625792,
        regionId: gazaRegion._id,
      },
      {
        Name: "Zachary Holmes",
        Origin: "South Sudan",
        Location_Type: "Urban",
        Event_Severity: 51.10686749016529,
        Economic_Loss_USD: 4435.45,
        Shelter_Status: "Partial",
        Food_Water_Access: "Partial",
        Health_Risk: "No Risk",
        Health_Severity_Score: 0.0,
        Family_Size: 2,
        Time_Since_Displacement_Days: 411,
        Displacement_Start_Date: "2024-03-11",
        Displacement_End_Date: "2024-05-04",
        Age: 77,
        Age_Group: "Elder (60+)",
        Shelter_Status_Num: 0.5,
        Food_Water_Access_Num: 0.5,
        Location_Type_Num: 0.3,
        Age_Group_Num: 0.7,
        Urgency_Score: 45.00337271497708,
        regionId: gazaRegion._id,
      },
      {
        Name: "Tanya Jones",
        Origin: "Côte d'Ivoire",
        Location_Type: "Rural",
        Event_Severity: 79.90731916930041,
        Economic_Loss_USD: 2081.95,
        Shelter_Status: "Full",
        Food_Water_Access: "None",
        Health_Risk: "No Risk",
        Health_Severity_Score: 0.0,
        Family_Size: 2,
        Time_Since_Displacement_Days: 220,
        Displacement_Start_Date: "2024-09-18",
        Displacement_End_Date: "2025-03-10",
        Age: 53,
        Age_Group: "Adult (18-59)",
        Shelter_Status_Num: 0.0,
        Food_Water_Access_Num: 1.0,
        Location_Type_Num: 0.7,
        Age_Group_Num: 0.0,
        Urgency_Score: 47.68773210520853,
        regionId: gazaRegion._id,
      },
      {
        Name: "Nicole Gray",
        Origin: "Monaco",
        Location_Type: "Rural",
        Event_Severity: 73.80531775104038,
        Economic_Loss_USD: 4343.94,
        Shelter_Status: "Partial",
        Food_Water_Access: "Full",
        Health_Risk: "No Risk",
        Health_Severity_Score: 0.0,
        Family_Size: 5,
        Time_Since_Displacement_Days: 486,
        Displacement_Start_Date: "2023-12-27",
        Displacement_End_Date: "2024-03-30",
        Age: 41,
        Age_Group: "Adult (18-59)",
        Shelter_Status_Num: 0.5,
        Food_Water_Access_Num: 0.0,
        Location_Type_Num: 0.7,
        Age_Group_Num: 0.0,
        Urgency_Score: 48.24937746924165,
        regionId: gazaRegion._id,
      },
      {
        Name: "Caleb Powell",
        Origin: "Cook Islands",
        Location_Type: "Urban",
        Event_Severity: 68.12125363487631,
        Economic_Loss_USD: 2975.67,
        Shelter_Status: "Partial",
        Food_Water_Access: "Partial",
        Health_Risk: "No Risk",
        Health_Severity_Score: 0.0,
        Family_Size: 5,
        Time_Since_Displacement_Days: 390,
        Displacement_Start_Date: "2024-04-01",
        Displacement_End_Date: "2024-07-27",
        Age: 38,
        Age_Group: "Adult (18-59)",
        Shelter_Status_Num: 0.5,
        Food_Water_Access_Num: 0.5,
        Location_Type_Num: 0.3,
        Age_Group_Num: 0.0,
        Urgency_Score: 46.24371624519159,
        regionId: gazaRegion._id,
      },
      {
        Name: "Katelyn Cox",
        Origin: "Martinique",
        Location_Type: "Urban",
        Event_Severity: 45.272909963730655,
        Economic_Loss_USD: 3698.18,
        Shelter_Status: "Partial",
        Food_Water_Access: "None",
        Health_Risk: "No Risk",
        Health_Severity_Score: 0.0,
        Family_Size: 5,
        Time_Since_Displacement_Days: 179,
        Displacement_Start_Date: "2024-10-29",
        Displacement_End_Date: "2025-05-13",
        Age: 54,
        Age_Group: "Adult (18-59)",
        Shelter_Status_Num: 0.5,
        Food_Water_Access_Num: 1.0,
        Location_Type_Num: 0.3,
        Age_Group_Num: 0.0,
        Urgency_Score: 45.82863846931695,
        regionId: gazaRegion._id,
      },
      {
        Name: "Danielle Mcdonald",
        Origin: "Martinique",
        Location_Type: "Rural",
        Event_Severity: 50.329952182164746,
        Economic_Loss_USD: 3806.44,
        Shelter_Status: "Partial",
        Food_Water_Access: "Full",
        Health_Risk: "No Risk",
        Health_Severity_Score: 0.0,
        Family_Size: 3,
        Time_Since_Displacement_Days: 335,
        Displacement_Start_Date: "2024-05-26",
        Displacement_End_Date: "2024-09-23",
        Age: 27,
        Age_Group: "Adult (18-59)",
        Shelter_Status_Num: 0.5,
        Food_Water_Access_Num: 0.0,
        Location_Type_Num: 0.7,
        Age_Group_Num: 0.0,
        Urgency_Score: 38.023419069792105,
        regionId: gazaRegion._id,
      },
      {
        Name: "Jeffery Ellis",
        Origin: "United Kingdom",
        Location_Type: "Urban",
        Event_Severity: 69.00072877814766,
        Economic_Loss_USD: 2781.82,
        Shelter_Status: "Partial",
        Food_Water_Access: "Full",
        Health_Risk: "Serious Injuries",
        Health_Severity_Score: 0.7,
        Family_Size: 3,
        Time_Since_Displacement_Days: 224,
        Displacement_Start_Date: "2024-09-14",
        Displacement_End_Date: "2025-08-07",
        Age: 61,
        Age_Group: "Elder (60+)",
        Shelter_Status_Num: 0.5,
        Food_Water_Access_Num: 0.0,
        Location_Type_Num: 0.3,
        Age_Group_Num: 0.7,
        Urgency_Score: 46.276684948816005,
        regionId: gazaRegion._id,
      }
    ];

    // Insert all individuals
    const individualIds: Id<"individuals">[] = [];
    for (const individual of individuals) {
      const id = await ctx.db.insert("individuals", individual);
      individualIds.push(id);
    }

    return individualIds;
  },
});